name: openaleabook
channels:
  - openalea3
  - conda-forge
  - fredboudon
dependencies:
  - openalea.plantgl
  - openalea.lpy
  - openalea.mtg
  - openalea.hydroshoot
  - openalea.hydroroot
  - openalea.plantscan3d
  - openalea.weberpenn
  - alinea.adel
  - alinea.caribu
  - alinea.astk
  - agroservices
  - weatherdata
  - pyqglviewer
  - jupyterlab>=3.0.16
  - jupyterlab_widgets
  - ipython=7
  - matplotlib
  - numpy=1.20.*
  - pandas
  - scipy
  - pip
  - voila 
  - voila-vuetify 
  - nodejs 
  - cufflinks-py 
  - ipyvuetify 
  - plotly
  - pyvis